### PR TITLE
Correct stats19 data

### PR DESCRIPTION
**Pull request by danielhills**
This PR fixes some data issues flagged by LCC, for the following collision IDs:
- 2021010289309
- 2018010106912
- 2018010115338

2021010289309 was being incorrectly filtered out, due to the distance threshold. For now, I've increased the threshold, but some further investigation may be needed into the junciton data in that area.

Both 2018010115338 & 2018010106912 were incorrectly labelled as 'not at a junction' in the data. Since these are fatal collisions they're important to have in the app, so this update contains some code to update these to be labelled as 'other_junction'.

### CODE REVIEW

**Review by folde01 — CHANGES_REQUESTED** [review]
The README says: 
> Activate the virtual environment: source/venv/activate 

That didn't work for me but `source venv/bin/activate` did.

Also `pip install -r requirements.txt` gives me this:

> ERROR: Could not find a version that satisfies the requirement convertbng==0.6.39 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23, 0.1.24, 0.1.25, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.7, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.6.41, 0.6.43)
> ERROR: No matching distribution found for convertbng==0.6.39

I changed it to 0.6.43 in requirements.txt and reran it and got this error:

> Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [2 lines of output]
>       Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'
>       A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> 

More later... I'll update this comment as I make progress.

**Comment by danielhills** [comment]
@folde01 - I've tried to clean up the requirements.txt a bit, didn't realise how big it was 140+ packages! Hopefully that helps.

We will probably need a better long term solution, ideally removing the need for specific version installs (==) and using >= instead.

**Comment by folde01** [comment]
Thanks @danielhills. I used `pipreqs` and got an even smaller `requirements.txt.` But whether I use mine or yours I get this:

> $ python src/01-download-tfl-data.py
> Processing: https://content.tfl.gov.uk/jan-sept-2022-gla-data-extract-attendant-provisional.csv
> Processing: https://content.tfl.gov.uk/jan-dec-2021-gla-data-extract-attendant.csv
> Processing: https://content.tfl.gov.uk/2020-gla-data-extract-attendant.csv
> Processing: https://content.tfl.gov.uk/2019-gla-data-extract-attendant.csv
> Processing: https://content.tfl.gov.uk/2018-data-files-attendant.csv
> Processing: https://content.tfl.gov.uk/2017-data-attendant.csv
> /home/jesse/projects/lcc-dangerous-junctions/src/01-download-tfl-data.py:138: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
>   collisions['date'] = pd.to_datetime(
> Traceback (most recent call last):
>   File "/home/jesse/projects/lcc-dangerous-junctions/src/01-download-tfl-data.py", line 190, in <module>
>     main()
>   File "/home/jesse/projects/lcc-dangerous-junctions/src/01-download-tfl-data.py", line 138, in main
>     collisions['date'] = pd.to_datetime(
>                          ^^^^^^^^^^^^^^^
>   File "/home/jesse/projects/lcc-dangerous-junctions/venv/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 1046, in to_datetime
>     cache_array = _maybe_cache(arg, format, cache, convert_listlike)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jesse/projects/lcc-dangerous-junctions/venv/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 250, in _maybe_cache
>     cache_dates = convert_listlike(unique_dates, format)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jesse/projects/lcc-dangerous-junctions/venv/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 453, in _convert_listlike_datetimes
>     return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jesse/projects/lcc-dangerous-junctions/venv/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 484, in _array_strptime_with_fallback
>     result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "pandas/_libs/tslibs/strptime.pyx", line 530, in pandas._libs.tslibs.strptime.array_strptime
>   File "pandas/_libs/tslibs/strptime.pyx", line 351, in pandas._libs.tslibs.strptime.array_strptime
> ValueError: time data "05/03/2020" doesn't match format "%d/%m/%Y %H:%M", at position 638. You might want to try:
>     - passing `format` if your strings have a consistent format;
>     - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
>     - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

"05/03/2020" is the date in the first line of https://content.tfl.gov.uk/2020-gla-data-extract-attendant.csv.  

Setting `format='mixed'` in the `pd_date_time` seems to fix the error.

**Comment by danielhills** [comment]
@folde01 - I think you've got a more recent version of pandas installed then what I was using (0.5.2), but I've gone ahead and updated the datetime functions anyway to work with pandas versions >= 2.0.0. Hopefully it works now?

Not great that tfl have used about 5 different datetime formats over the years...

**Comment by folde01** [comment]
Yep thanks @danielhills it works.. now on to seeing what it all does!

**Comment by folde01** [comment]
@danielhills I'm just starting to learn about dataframes. What happens at https://github.com/londoncyclingcampaign/lcc-dangerous-junctions/blob/0ded519b86ed1f1d5d89a1d806926adae80a79ef/src/01-download-tfl-data.py#L75 where you use the `alias_df['type'] == alias_type` as an index value of alias_df?  Is `alias_df['type'] == alias_type` a boolean?

**Comment by danielhills** [comment]
It's an array of booleans, so a true / false value for each row in the dataframe, which allows for easy filtering on a certain column.

**Comment by folde01** [comment]
@danielhills I ran `streamlit run app.py` but it couldn't find a `secrets.toml` file, so I made one following https://docs.streamlit.io/library/advanced-features/secrets-management but I'm not sure what to put in it, as I get this:

> KeyError: 'st.secrets has no key "junctions_15". Did you forget to add it to secrets.toml or the app settings on Streamlit Cloud? More info: https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management'

**Comment by danielhills** [comment]
Oops that's my mistake @folde01, the secrets.toml file is needed otherwise it won't be able to read in the necessary data.

Will send you the file separately.

**Pull request merged**
